package com.magtable.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author David
 *
 * This class it MOSTLY auto generated by JPA persistence unit, model for the userLevel table
 */

@Entity
public class Userlevel implements Serializable {

    /** Attributes **/

    private byte levelId;
    private String description;

    /** Getters and Setters **/

    @Id
    @Column(name = "levelID")
    public byte getLevelId() {
        return levelId;
    }

    public void setLevelId(byte levelId) {
        this.levelId = levelId;
    }

    @Basic
    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /** Auto Generated helped methods **/

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Userlevel userlevel = (Userlevel) o;
        return levelId == userlevel.levelId &&
                Objects.equals(description, userlevel.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(levelId, description);
    }
}
